### ISSUE TITLE
下载编译失败

### ISSUE THREAD

**Issue by jonathan2004** [WeBankFinTech/WeCross#97]
按照文档，下载代码并执行编译，结果失败。

> Task :test

com.webank.wecross.test.network.NetworkManagerTest > addAndRemoveConcurrentTest STANDARD_OUT
    2019-12-06 10:46:15.523 [Thread-7] INFO  NetworkManagerTest(:) - Remove resource
    ... ...
    com.webank.wecross.test.peer.PeerResourcesTest > noMyselfTest STANDARD_OUT
    2019-12-06 10:46:15.734 [Test worker] ERROR PeerResources(:) - Myself resources has not been set.
    2019-12-06 10:46:15.734 [Test worker] ERROR PeerResources(:) - Myself resources has not been set.
  ... ...
  2019-12-06 10:46:21.192 [Test worker] ERROR ResourceLeakDetector(:) - LEAK: HashedWheelTimer.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
    Recent access records: 
    Created at:
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:284)
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:217)
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:196)
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:178)
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:162)
        io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:121)
        com.webank.wecross.p2p.netty.P2PService.<init>(P2PService.java:33)
        com.webank.wecross.test.Mock.MockP2PService.<init>(MockP2PService.java:8)
        com.webank.wecross.test.peer.PeerManagerTest.newMockPeerManager(PeerManagerTest.java:102)
        com.webank.wecross.test.peer.PeerManagerTest.syncByRequestPeerInfo(PeerManagerTest.java:128)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        ....
       2019-12-06 10:46:21.254 [Test worker] ERROR WeCrossHost(:) - Startup host error: {}
    java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_221]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_221]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_221]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_221]
        at com.webank.wecross.p2p.netty.common.Utils.validIP(Utils.java:33) ~[main/:?]
        at com.webank.wecross.p2p.config.P2PConfig.validConfig(P2PConfig.java:140) ~[main/:?]
        at com.webank.wecross.p2p.netty.Initializer.start(Initializer.java:152) ~[main/:?]
        at com.webank.wecross.p2p.netty.P2PService.start(P2PService.java:93) ~[main/:?]
        at com.webank.wecross.host.WeCrossHost.start(WeCrossHost.java:26) ~[main/:?]
       ... ...

      > Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 255
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.2.1/userguide/java_testing.html#sec:test_execution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 9s

**Comment by JimmyShi22** [comment]
目前未发布，还在开发中，可用如下命令代替gradle build
``` shell
gradle assemble
```
